### ISSUE TITLE
Hand off project

### ISSUE THREAD

**Issue by landau** [jfromaniello/passport-hawk#7]
Is there anyone willing to take this project and update it? It's a really small project. I'd be willing to take it over if need be.

**Comment by jfromaniello** [comment]
I misa the notification for the other PR but Im still alive, send me a PR and I'd merge and vive you acces as maintainer/author. Thanks

**Comment by jfromaniello** [comment]
Thanks for the heads up, I just published `v1.0.0`.

**Comment by landau** [comment]
Cool. Actually, I played with my own implementation yesterday and found that passport messes with `hawk`'s header and therefore renders the client unable to `verify` the response.

**Comment by jfromaniello** [comment]
@landau I'm not sure if is the same problem I had, but I've to use `req.originalUrl` instead of `req.url` because if you `app.use('/api', hawk)` the req.url will have everything but `/api`.

So, I use always req.originalUrl. This is not passport fault but express changing the meaning of the `req.url` prop.

Besides that I don't think passport changes any other header

**Comment by landau** [comment]
Hmm. I'll try that out! Thanks.
